language: python
sudo: true
python:
- 3.6
addons:
  apt_packages:
  - libcups2-dev
services:
- mysql
branches:
  only:
  - develop
install:
- pip install --upgrade pip
- pip install flake8
- pip install coveralls
- pip install mysqlclient
- pip install -e .
- pip install -q -r requirements.txt
before_script:
- flake8 tp-subject
- python manage.py makemigrations
- python manage.py migrate
- mysql -e 'create database edc character set utf8;'
script:
- coverage run --source=tp_subject manage.py test
after_success:
- coveralls
