# Generated by Django 2.0.4 on 2018-04-19 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tp_subject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='demographic',
            name='number_wives',
            field=models.IntegerField(blank=True, null=True, verbose_name='If subject is a woman, how many wives does the husband have (traditional wives and subject included)'),
        ),
        migrations.AlterField(
            model_name='demographic',
            name='number_wives_men',
            field=models.IntegerField(blank=True, null=True, verbose_name='If subject is a man, how many wives does he have (traditional marriage included)?'),
        ),
        migrations.AddField(
            model_name='education',
            name='job_type',
            field=models.ManyToManyField(to='tp_subject.Work', verbose_name='If subject is a woman, how many wives does the husband have (traditional wives and subject included)'),
        ),
    ]
