# Generated by Django 2.0.4 on 2018-04-19 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tp_subject', '0002_auto_20180419_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='salary',
            field=models.CharField(choices=[('none', 'No income'), ('1-199 pula', '1-199 pula'), ('200-499 pula', '200-499 pula'), ('500-999 pula', '500-999 pula'), ('1000-4999 pula', '1000-4999 pula'), ('5000-10,000 pula', '5000-10,000 pula'), ('more than 10,000 pula', 'More than 10,000 pula'), ("don't want to answer", "Don't want to answer")], default='None', max_length=20, verbose_name='In the past month, how much money did you earn from workyou did or received in payment?'),
        ),
        migrations.AddField(
            model_name='education',
            name='work_done',
            field=models.CharField(choices=[('farmer (own land)', 'Farmer (own land)'), ('farm work on employers land', 'Farm work on employers land'), ('domestic worker', 'Domestic worker'), ('work in bar/ hotel/ guest house/ entertainment venue', 'Work in bar/ hotel/ guest house/ entertainment venue'), ('fishing', 'Fishing'), ('mining', 'Mining'), ('Tourism/game parks', 'Tourism/game parks'), ('working in shop / small business', 'Working in shop / small business'), ('informal selling', 'Informal selling'), ('commercial sex work', 'Commercial sex work'), ('transport (trucker/ taxi driver)', 'Transport (trucker/ taxi driver)'), ('factory worker', 'Factory worker'), ('guard (security company)', 'Guard (security company)'), ('police/ Soldier', 'Police/ Soldier'), ('clerical and office work', 'Clerical and office work'), ('government worker', 'Government worker'), ('teacher', 'Teacher'), ('health care worker', 'Health care worker'), ('other professional', 'Other professional'), ("don't want to answer", "Don't want to answer"), ('other', 'Other')], default='Other', max_length=50, verbose_name='Describe the work that you do or did in your most recent job. If you have more than one profession, choose the one you spend the most time doing'),
        ),
        migrations.RemoveField(
            model_name='education',
            name='job_type',
        ),
        migrations.AddField(
            model_name='education',
            name='job_type',
            field=models.CharField(choices=[('occassional or Casual', 'Occassional or Casual employment (piece job)'), ('seasonal employment', 'Seasonal employment'), ('formal wage employment (full-time)', 'Formal wage employment (full-time)'), ('formal wage employment (part-time)', 'Formal wage employment (part-time)'), ('self-employed in agriculture', 'Self-employed in agriculture'), ('self-employed making money, full time', 'Self-employed making money, full time'), ('self-employed making money, part time', 'Self-employed making money, part time'), ("don't want to answer", "Don't want to answer"), ('other', 'Other')], default='Other', max_length=50, verbose_name='In your main job, what type of work do you do?'),
        ),
        migrations.DeleteModel(
            name='Work',
        ),
    ]
