# Generated by Django 2.0.4 on 2018-04-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tp_subject', '0004_auto_20180419_0657'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityEngagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('how_active', models.CharField(choices=[('very active', 'Very active'), ('somewhat active', 'Somewhat active'), ('not active', 'Not active'), ("don't want to answer", "Don't want to answer")], max_length=10, verbose_name='How active are you in community activities such as burial society, Motshelo, Syndicate, PTA, VDC(Village Developement Committee), Mophato and development of the community that surrounds you??')),
                ('voted', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('not applicable', 'N/A'), ("don't want to answer", "Don't want to answer")], default='Other', max_length=50, verbose_name='Did you vote in the last local government election?')),
                ('major_problems', models.CharField(choices=[('HIV/AIDS', 'Single'), ('Schools', 'Married'), ('Sewer', 'Divorced'), ('Unemployment', 'Unemployment'), ('Roads', 'Roads'), ('Water', 'Water'), ('House', 'House'), ('Malaria', 'Malaria')], default='Other', max_length=50, verbose_name='What are the major problems in this neighbourhood?')),
                ('work_together', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ("don't know", "Don't know"), ("don't want to answer", "Don't want to answer")], default='None', max_length=20, verbose_name='If there is a problem in this neighborhood, do the adults work together in solving it?')),
            ],
        ),
    ]
